title: Keen notes
description: Researcher
# Minima theme shows the site title at least twice in the footer, as a fallback if there is no author, so let's add author:
author: VS
github_username: VolShyn

email: vol.shynk@gmail.com
# twitter_username:

# Set this to true to get LaTeX math equation support
use_math: True

google_analytics:

theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled: true
  strip_title: true
  collections: false

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

future: true
