title: Keen notes
description: Researcher
github_username: VolShyn


email: vol.shynk@gmail.com
# twitter_username:

# Set this to true to get LaTeX math equation support
use_math: True

google_analytics:

theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata


collections:
  math: 
    output: true
  python:
    output: true
    

# output: true

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
